### ISSUE TITLE
楼主测过在voc数据集上的mAP吗？

### ISSUE THREAD

**Issue by laidy3** [yangxue0827/FPN_Tensorflow#10]
如题，感谢楼主的代码实现

**Comment by yangxue0827** [comment]
效果不好，目前还未找出原因，在单类或者少类的情况下效果还不错。




| |
杨学
邮箱：yangxue0827@126.com
|

签名由 网易邮箱大师 定制

在2018年04月02日 20:34，Xiaoyao-Lee 写道：

如题，感谢楼主的代码实现

**Comment by yeyuanzheng177** [comment]
voc上img/faster_rcnn_predict/image/0  只训练某一类的 比如person这个类别

**Comment by yeyuanzheng177** [comment]
没找到原因

**Comment by niuniu111** [comment]
你有没有试过VGG网络？

**Comment by yangxue0827** [comment]
We modified the Faster-RCNN to make its performance more robust and excellent, and achieved better performance in the voc2007 (the value of mAP is around 75 based on resnet50, and the figure for resnet101 and mobilenetv2 are 77 and 50 respectively) without add any extra data. The code will be uploaded in https://github.com/DetectionTeamUCAS. We also will update other detection frameworks in the future.

**Comment by leishi2018** [comment]
楼主什么时候更新，这个code我在VOC07/12上面训练。用于识别多类物体，但盒子的ratios和factors设置好像比较影响训练效果。最后识别的效果也不好，一幅图里面对人的识别效果比较好大多能框出来，但是车，火车，猫，狗什么的就识别的不行。。你们的更新适用于多物体识别的吗？谢谢

**Comment by yangxue0827** [comment]
适用于多类检测，而且指标能比较高，代码正在完善和整理，可以先关注https://github.com/DetectionTeamUCAS。

**Comment by leishi2018** [comment]
好的，谢谢

**Comment by leishi2018** [comment]
楼主，由于这个代码在VOC数据集上训练多种物体效果不好。得知训练2个或者少类物体效果还行。那我想仍然在VOC上面做训练，这个时候如果我想训练3类让class_num=3，其他的也改好，那训练集图片是不是只能含有这三类的图呢，还是我仍然可以使用VOC里面的20类的图片（当然包括这三类的图），不更改直接用呢。

**Comment by yangxue0827** [comment]
@Xiaoyao-Lee @yeyuanzheng177 @niuniu111 @leishi2018 https://github.com/DetectionTeamUCAS/Faster-RCNN_Tensorflow

**Comment by yangxue0827** [comment]
Recommend improved code: https://github.com/DetectionTeamUCAS/FPN_Tensorflow. @laidy3 @yeyuanzheng177 @niuniu111 @leishi2018
