### ISSUE TITLE
TypeError: cond() got an unexpected keyword argument 'true_fn', i am puzzled with this problem, do you meet this problem before, can you help me?

### ISSUE THREAD

**Issue by chinapanda** [yangxue0827/FPN_Tensorflow#13]
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
tfrecord path is --> /home/hley/software/FPN_Tensorflow/data/tfrecords/pascal_train*
Traceback (most recent call last):
  File "train.py", line 229, in <module>
    train()
  File "train.py", line 34, in train
    is_training=True)
  File "../data/io/read_tfrecord.py", line 82, in next_batch
    is_training=is_training)
  File "../data/io/read_tfrecord.py", line 57, in read_and_prepocess_single_img
    target_shortside_len=shortside_len)
  File "../data/io/image_preprocess.py", line 26, in short_side_resize
    false_fn=lambda: (target_shortside_len * h//w,  target_shortside_len))
TypeError: cond() got an unexpected keyword argument 'true_fn'

**Comment by yangxue0827** [comment]
I guess this function is changed between the different version of tensorflow




| |
杨学
邮箱：yangxue0827@126.com
|

签名由 网易邮箱大师 定制

On 04/28/2018 16:07, Nicholas wrote:

I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
tfrecord path is --> /home/hley/software/FPN_Tensorflow/data/tfrecords/pascal_train*
Traceback (most recent call last):
File "train.py", line 229, in
train()
File "train.py", line 34, in train
is_training=True)
File "../data/io/read_tfrecord.py", line 82, in next_batch
is_training=is_training)
File "../data/io/read_tfrecord.py", line 57, in read_and_prepocess_single_img
target_shortside_len=shortside_len)
File "../data/io/image_preprocess.py", line 26, in short_side_resize
false_fn=lambda: (target_shortside_len * h//w, target_shortside_len))
TypeError: cond() got an unexpected keyword argument 'true_fn'

**Comment by chinapanda** [comment]
thanks! that is right, i have already corrected it, i want to know  how much data to train these models just for plane. thanks!

**Comment by niuniu111** [comment]
I also met this problem, what should I do ？

**Comment by chinapanda** [comment]
Change the version of tensorflow into 1.2. look this configure [ ubuntu(Encoding problems may occur on windows) + python2 + tensorflow1.2 + cv2 + cuda8.0 + GeForce GTX 1080 ]
