### ISSUE TITLE
Does this code have a corresponding Windows version?

### ISSUE THREAD

**Issue by niuniu111** [yangxue0827/FPN_Tensorflow#14]

**Comment by yangxue0827** [comment]
I think this code is supported on windows.

**Comment by niuniu111** [comment]
I am very glad to receive your mail. Thank you very much for your impatient reply. I ran on windows again, but every time I make a more than 700 step, I will make mistakes:
tensorflow.python.framework.errors_impl.UnknownError: OverflowError: Python int too large to convert to C long
[[Node: fast_rcnn_loss/PyFunc_1 = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_INT32], Tout=[DT_UINT8], token="pyfunc_7", _device="/job:localhost/replica:0/task:0/cpu:0"](fast_rcnn_loss/Squeeze_1, fast_rcnn_loss/mul_1, fast_rcnn_loss/strided_slice_1)]]
原因好像是Ubuntu和windows存储数据问题，我将生成tfrecord数据类型更改为float类型，出现另一种错误，改了好多次，还是不行

**Comment by wwwzxoe303com** [comment]
I run this code on windows, but this convert_data_to_tfrecord.py  build .tfrecord is 0kb. I don't know why. In CMD has no warning and error.

**Comment by liulonghoi** [comment]
请问你解决这个问题没?我是在Linux上训练的，然后想用训练好的模型再windows上测试，然后出现问题。
