### ISSUE TITLE
anchor error!

### ISSUE THREAD

**Issue by lfdeep** [yangxue0827/FPN_Tensorflow#24]
你好！请问一下
BASE_ANCHOR_SIZE_LIST = [15, 25, 40, 60, 80]
LEVEL = ['P2', 'P3', 'P4', 'P5', "P6"]
STRIDE = [4, 8, 16, 32, 64]
ANCHOR_SCALES = [1.]
ANCHOR_RATIOS = [1, 0.5, 2, 1 / 3., 3., 1.5, 1 / 1.5]
SCALE_FACTORS = [10., 10., 5., 5.]
OUTPUT_STRIDE = 16

请问一下这几个参数的意义是什么？

**Comment by Ostnie** [comment]
@lfdeep 建议你从RCNN一路看到faster RCNN，这样你会理解的更深刻
