### ISSUE TITLE
直接用作者提供的权重模型无法得到正确的result的图片

### ISSUE THREAD

**Issue by Ostnie** [yangxue0827/FPN_Tensorflow#25]
我直接使用作者在output里面的模型运行程序，生成的result图片的检测
![sample12 tif_fpn](https://user-images.githubusercontent.com/31840090/41341789-29aeb672-6f2d-11e8-9d53-dff92d79d09d.jpg)
基本没有准确的，请问这是怎么回事？

**Comment by yangxue0827** [comment]
你没有加载训练好的权重，加载的是预训练权重。请检查权重的路径是否正确，若不正确默认加载与训练权重。

**Comment by Ostnie** [comment]
@yangxue0827 预训练好的权重是否是您在output文件夹下面那五个压缩包，我的确已经解压，或者是指resnet101，这个我也下载并解压到相应文件夹，并且在运行程序时看到了restore model的字样。

或者我可能漏了什么步骤？我就是下载了各种需要的东西，然后修改了cfg的根目录，就直接运行，结果就是这样。

**Comment by yangxue0827** [comment]
五个文件夹解压后应该是只有一个文件夹，你可以把resnet101的权重先删了，看看导入的是哪个权重。另外导入训练好的权重时应该会打印出导入权重的名字的。

**Comment by yangxue0827** [comment]
@Ostnie https://github.com/DetectionTeamUCAS/Faster-RCNN_Tensorflow
