### ISSUE TITLE
batchsize=1？大目标效果不太好？

### ISSUE THREAD

**Issue by xuhongwei237** [yangxue0827/FPN_Tensorflow#28]
你好，感谢你的代码。我有两个问题，第一，batchsize=1是不是只能增加迭代次数才能使训练的效果好?如果是那至少应该迭代多少次呢?第二，我迭代50000次训练完以后进行inference，发现小目标还能检测出一些，而大目标一个都检测不到，请问这是怎么回事，增加迭代次数能使检测大目标效果提升吗？

**Comment by yangxue0827** [comment]
这个代码目前对少类目标检测效果还不错。batchsize只能是1。如果大目标效果不好，你可以调整一下anchor的比例和大小，保证能覆盖到你的目标，可以从tensorboard观察。以后会在https://github.com/DetectionTeamUCAS 上传修改后的检测代码，效果和论文差不多 @xuhongwei237  。

**Comment by xuhongwei237** [comment]
好的，谢谢，期待能早点看到修改后的代码。

**Comment by yangxue0827** [comment]
https://github.com/DetectionTeamUCAS/Faster-RCNN_Tensorflow @xuhongwei237

**Comment by yangxue0827** [comment]
Recommend improved code: https://github.com/DetectionTeamUCAS/FPN_Tensorflow. @xuhongwei237
