### ISSUE TITLE
队列关闭

### ISSUE THREAD

**Issue by PKUzouyajun** [yangxue0827/FPN_Tensorflow#29]

**Comment by PKUzouyajun** [comment]
PaddingFIFOQueue '_2_get_batch/batch/padding_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: get_batch/batch = QueueDequeueManyV2[component_types=[DT_STRING, DT_FLOAT, DT_INT32, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](get_batch/batch/padding_fifo_queue, get_batch/batch/n)]]

**Comment by leetesua** [comment]
have you solve this ?  i met the same question
