### ISSUE TITLE
Where did the predict_dict.pkl and gtboxes_dict.pkl come from and how to generate them?

### ISSUE THREAD

**Issue by Kongsea** [yangxue0827/FPN_Tensorflow#3]
It seems that 'predict_dict.pkl' and 'gtboxes_dict.pkl' are required to run eval.py to evaluate the model. Could you please tell me where are the two files from or  how to generate the two files?
Thank you. @yangxue0827

**Comment by yangxue0827** [comment]
These two files are generated when you run eval.py.




| |
杨学
邮箱：yangxue0827@126.com
|

签名由 网易邮箱大师 定制

On 03/08/2018 17:05, Kongsea wrote:

It seems that 'predict_dict.pkl' and 'gtboxes_dict.pkl' are required to run eval.py to evaluate the model. Could you please tell me where are the two files from or how to generate the two files?
Thank you. @yangxue0827

**Comment by Kongsea** [comment]
Thank you.
I found you have commented the code to generate these two pkl files:

`eval_dict_convert(img_num)`

in [the code file](https://github.com/yangxue0827/FPN_Tensorflow/blob/master/tools/eval.py#L295).

**Comment by niuniu111** [comment]
when I run eval.py,Error running 'eval',java.util.zip.ZipException:incorrect header check, I don't kown how to do it
