### ISSUE TITLE
Is this Resnet+FPN?

### ISSUE THREAD

**Issue by murdockhou** [yangxue0827/FPN_Tensorflow#32]
Thanks for your work, it's amazing! I am totally a new guy in DL area, i want to know this code is about Resnet + FPN? I'm not clear about this. 

What i know now is that FPN is based on some backbone network such as ResNet, VGG, or other networks.

Thanks for your any help!

**Comment by yangxue0827** [comment]
Yes, it supports res101 and res50.

**Comment by murdockhou** [comment]
Thanks， i'll check out code carefully.

**Comment by yangxue0827** [comment]
Recommend improved code: https://github.com/DetectionTeamUCAS/FPN_Tensorflow. @murdockhou
