### ISSUE TITLE
About ResNet and Faster_rcnn

### ISSUE THREAD

**Issue by murdockhou** [yangxue0827/FPN_Tensorflow#33]
Hi, thanks for your work firstly. I'm looking at your code and there is somewhere confused me. In the train step, as your instructor, i can download resnet-50 or resnet-101 pretrained model to run " python train.py" command line.  The code in tools/train.py, i saw that there are some sentences like 

`tf.summary.scalar('rpn/rpn_total_loss')` or `tf.summary.scalar('fast_rcnn/fast_rcnn_total_loss')` 

so it confused me. The train model is resnet or fast-rcnn or others? And i did not see 'FPN' at all. May be something i understand wrong about the networks. I'll very appreciate for your reply.

Thanks.

**Comment by murdockhou** [comment]
it's a little clear for me. The function `build_rpn.RPN` is the resnet + FPN model?  and you have compare this RPN model with fast-rcnn model?

**Comment by murdockhou** [comment]
![selection_020](https://user-images.githubusercontent.com/18358653/43257405-54a7e9ba-9102-11e8-9486-b7bd39d200c6.png)

when you build RPN, the function "get_feature_maps", for every resnet block, why not choose the last residual block? such like:
`"C2": self.share_net["resnet_v1_50/block1/unit_3/bottleneck_v1"]`

**Comment by yangxue0827** [comment]
This has to do with the way slim implements resnet. @murdockhou

**Comment by murdockhou** [comment]
Thanks. The RPN modle i think is the 'ResNet + FPN' in your code, is it right?

**Comment by yangxue0827** [comment]
yes. @murdockhou
