### ISSUE TITLE
anchor正负样本标定中对应的gtbox index确定

### ISSUE THREAD

**Issue by WeichengDDD** [yangxue0827/FPN_Tensorflow#37]
你好，libs/rpn/build_rpn.py中gtbox index确定过程
matched_gtboxes_index = tf.cast(tf.argmax(ious, axis=1), tf.int32)
如果某anchor是因为与gtbox_i的iou最大被标为正样本，但gtbox_i_iou在[gtbox_1_iou, gtbox_2_iou...]不为最大值，此时gtbox index 应该取gtbox_i的还是直接取iou最大的？

**Comment by yangxue0827** [comment]
@WeichengDDD  你好，是前者。你应该区分一下在取gtbox index 和采样正样本的区别。gtbox index取决于anchor和哪一个gtbox的iou最大，而正样本的判断标准是:
1. anchor和gtbox的iou的最大值是否超过阈值
2. 这个anchor和某个gtbox的iou是所有anchor中最大的

**Comment by WeichengDDD** [comment]
好的，谢谢
