### ISSUE TITLE
This project is only detecting one class?

### ISSUE THREAD

**Issue by duyuting** [yangxue0827/FPN_Tensorflow#4]
how to detect three classess ,change the --dataset='1 2 3'?????

**Comment by Kongsea** [comment]
It can detect more than one class.
I have used it to detect **two** classes successfully.
But the accuracy is not as good as Facebook's **Detectron**.

**Comment by yangxue0827** [comment]
You only need to modify the parameter CLASS_NUM in cfgs.py. However, as Kongsea say, the accuracy is not quiet well, hope you can find out the problem and contact me.

**Comment by yangxue0827** [comment]
@duyuting @Kongsea https://github.com/DetectionTeamUCAS/Faster-RCNN_Tensorflow

**Comment by yangxue0827** [comment]
Recommend improved code: https://github.com/DetectionTeamUCAS/FPN_Tensorflow. @duyuting
