### ISSUE TITLE
请问我用该代码跑HRSC舰船数据集 训练的时候RPN产生的候选框除了正确区域的几个框以外，其余框都特别小

### ISSUE THREAD

**Issue by PURE-melo** [yangxue0827/FPN_Tensorflow#57]
一开始训练时还没有这种情况，运行几千步以后，rpn就成这样了，想请教您一下。

![image](https://user-images.githubusercontent.com/34188839/55785617-587b5880-5ae5-11e9-86b5-e02e9b849bda.png)

**Comment by PURE-melo** [comment]
我怀疑是因为您的代码中neg anchor是与目标IOU小于0.2的框组成的，会不会是因为没有考虑那些IOU=0的忽略了的框。

**Comment by PURE-melo** [comment]
已解决。。。。先训练了5000步rpn，再训练fasterrcnn就好了

**Comment by muyangmuzi** [comment]
你好，我先问一下如何单独训练rpn

**Comment by PURE-melo** [comment]
就是把fastrcnn部分先去掉 只用rpn损失进行训练 705286770 邮箱705286770@qq.com 签名由 网易邮箱大师 定制 在2019年05月16日 16:24，Mumaping 写道： 你好，我先问一下如何单独训练rpn — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by zy5037** [comment]
你好，在HRSC数据集上检测的结果有多高呢，有更改超参数吗
