### ISSUE TITLE
How to understand this step(Train1)?

### ISSUE THREAD

**Issue by VennShi** [yangxue0827/FPN_Tensorflow#6]
> Train1.Modify $FPN_ROOT/libs/lable_name_dict/***_dict.py, corresponding to the number of categories in the configuration file

I don't know what should I modify in label_dict.py and what is the configuration file.
I skip this step,and some problem appear when running train.py .The problem is like this.

`W tensorflow/core/framework/op_kernel.cc:1158] Out of range: PaddingFIFOQueue '_1_get_batch/batch/padding_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
`

**Comment by niuniu111** [comment]
I also encountered this problem, do not know why?
