### ISSUE TITLE
fpn网络定义在哪呢？

### ISSUE THREAD

**Issue by itisianlee** [yangxue0827/FPN_Tensorflow#9]
实在是找不到你fpn层的定义在哪...

**Comment by yangxue0827** [comment]
[here](https://github.com/yangxue0827/FPN_Tensorflow/blob/master/libs/rpn/build_rpn.py#L106)

**Comment by Superlee506** [comment]
@itisianlee @yangxue0827  In fpn, the original paper also contains "p6", but in your project, I just find "p2, p3, p4, p5". So, where is "P6"? Do I miss someting?

**Comment by yangxue0827** [comment]
As paper write, P6 is used in rpn stage, but not in second stage.
